# Generated by Django 5.2.12 on 2026-03-05 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('quantite_stock', models.IntegerField(default=0)),
                ('seuil_minimum', models.IntegerField(default=5)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Pièce',
            },
        ),
        migrations.CreateModel(
            name='Appareil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_appareil', models.CharField(choices=[('PC', 'PC'), ('Laptop', 'Laptop'), ('Imprimante', 'Imprimante'), ('Serveur', 'Serveur'), ('Autre', 'Autre')], max_length=50)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('sous_garantie', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appareils', to='interventions.client')),
            ],
            options={
                'verbose_name': 'Appareil',
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('description', models.TextField()),
                ('type_service', models.CharField(choices=[('reparation', 'Réparation matériel'), ('installation', 'Installation logiciel'), ('configuration', 'Configuration réseau'), ('maintenance', 'Maintenance préventive'), ('depannage', 'Dépannage à distance')], max_length=50)),
                ('canal_entree', models.CharField(choices=[('telephone', 'Téléphone'), ('boutique', 'Boutique'), ('email', 'Email')], max_length=20)),
                ('urgence', models.CharField(choices=[('faible', 'Faible'), ('normale', 'Normale'), ('haute', 'Haute'), ('critique', 'Critique')], default='normale', max_length=20)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('diagnostique', 'Diagnostiqué'), ('assigne', 'Assigné'), ('en_cours', 'En cours'), ('attente_pieces', 'En attente pièces'), ('termine', 'Terminé'), ('valide', 'Validé'), ('facture', 'Facturé'), ('cloture', 'Clôturé')], default='nouveau', max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_planifiee', models.DateTimeField(blank=True, null=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('duree_estimee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duree_reelle', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('diagnostic_ia', models.TextField(blank=True, null=True)),
                ('notes_technicien', models.TextField(blank=True, null=True)),
                ('appareil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='interventions.appareil')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='interventions.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intervention',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('montant_main_oeuvre', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_pieces', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_deplacement', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('intervention', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='facture', to='interventions.intervention')),
            ],
            options={
                'verbose_name': 'Facture',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_entree', models.TextField()),
                ('categorie_panne', models.CharField(blank=True, max_length=100)),
                ('causes_probables', models.TextField(blank=True)),
                ('pieces_suggerees', models.TextField(blank=True)),
                ('complexite', models.CharField(blank=True, choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('elevee', 'Élevée')], max_length=20)),
                ('duree_estimee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('score_confiance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('intervention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic', to='interventions.intervention')),
            ],
        ),
        migrations.CreateModel(
            name='PieceUtilisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_utilisees', to='interventions.intervention')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interventions.piece')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('genere_par_ia', models.BooleanField(default=False)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('intervention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='interventions.intervention')),
            ],
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('specialite', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('reseau', 'Réseau'), ('maintenance', 'Maintenance')], max_length=50)),
                ('competences', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('tarif_horaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Technicien',
            },
        ),
        migrations.AddField(
            model_name='intervention',
            name='technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='interventions.technicien'),
        ),
    ]
