# Generated by Django 5.2.12 on 2026-05-15 10:45

import django.db.models.deletion
import interventions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0002_agent_profilutilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=interventions.models.chemin_image_intervention)),
                ('type_image', models.CharField(choices=[('avant', 'Photo avant intervention'), ('apres', 'Photo après intervention'), ('panne', 'Photo de la panne'), ('piece', 'Photo de la pièce'), ('document', 'Document / Bon de livraison'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='interventions.intervention')),
            ],
            options={
                'verbose_name': "Image d'intervention",
                'ordering': ['-date_ajout'],
            },
        ),
    ]
