# Generated by Django 5.2.12 on 2026-05-22 11:34

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0003_imageintervention'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageintervention',
            options={'ordering': ['date_ajout'], 'verbose_name': "Image d'intervention", 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterField(
            model_name='imageintervention',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='imageintervention',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='imageintervention',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='interventions.intervention', verbose_name='Intervention'),
        ),
        migrations.AlterField(
            model_name='imageintervention',
            name='type_image',
            field=models.CharField(choices=[('avant', 'Avant intervention'), ('apres', 'Après intervention'), ('panne', 'Photo de la panne'), ('piece', 'Photo de la pièce'), ('document', 'Document'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Type'),
        ),
    ]
