# Generated by Django 5.2.12 on 2026-06-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0004_alter_imageintervention_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appareil',
            options={'ordering': ['-cree_le'], 'verbose_name': 'Appareil'},
        ),
        migrations.RenameField(
            model_name='appareil',
            old_name='date_achat',
            new_name='date_fin_garantie',
        ),
        migrations.AddField(
            model_name='appareil',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='appareil',
            name='marque',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appareil',
            name='numero_serie',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appareil',
            name='type_appareil',
            field=models.CharField(choices=[('ordinateur', 'Ordinateur'), ('imprimante', 'Imprimante'), ('serveur', 'Serveur'), ('reseau', 'Réseau'), ('autre', 'Autre')], default='ordinateur', max_length=20),
        ),
    ]
