# Generated by Django 5.2.12 on 2026-06-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0005_alter_appareil_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('responsable', 'Responsable'), ('agent', "Agent d'accueil"), ('technicien', 'Technicien')], default='agent', max_length=20),
        ),
    ]
